name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.x.x'
  NODE_VERSION: '20.x'
  SOLUTION_PATH: 'src/RobGreenEngineering.sln'
  PROJECT_PATH: 'src/RobGreenEngineering/RobGreenEngineering.csproj'

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o public -p:GHPages=true -p:GHPagesBase="/"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public/wwwroot
        force_orphan: true