name: NPM outdated

# Run workflow on pull request to the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
  
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'
  PROJECT_DIR: 'src/RobGreenEngineering'

jobs:
  npm-outdated:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: NPM install
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm install

    - name: NPM update check
      uses: MeilCli/npm-update-check-action@v4 
      id: npm-outdated
      with:
        execute_directories: ${{ env.PROJECT_DIR }}
        output_text_style: short

    - name: Create npm outdated comment
      id: npm-outdated-comment
      working-directory: ${{ env.PROJECT_DIR }}
      shell: bash
      run: |
        if [[ "${{ steps.npm-outdated.outputs.has_npm_update }}" = "false" ]]; then
            printf "## No outdated npm packages found :rocket:" >> npm_outdated.md
            echo "NPM_SHOULD_FAIL=false" >> "$GITHUB_OUTPUT"
        else
            OUTPUT=`npm outdated`
            echo "$OUTPUT"
            # printf "$OUTPUT" >> npm_outdated.md
            printf "${{ steps.npm-outdated.outputs.npm_update_text }}" >> npm_outdated.md
            echo ' ' | cat - npm_outdated.md > temp && mv temp npm_outdated.md
            echo '> Outdated npm packages found, update if possible' | cat - npm_outdated.md > temp && mv temp npm_outdated.md
            echo '> [!WARNING]' | cat - npm_outdated.md > temp && mv temp npm_outdated.md
            echo "NPM_SHOULD_FAIL=false" >> "$GITHUB_OUTPUT"
        fi

    - name: NPM outdated PR comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: "${{ env.PROJECT_DIR }}/npm_outdated.md"
        comment_tag: npm_outdated