name: Outdated package checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]    
    paths:
      - '.github/workflows/outdated.yml'
      - 'src/**'
  
  workflow_dispatch:

env:
  SOLUTION_PATH: 'src/RobGreenEngineering.sln'
  PROJECT_DIR: 'src/RobGreenEngineering'
  EXCLUDE_PACKAGES: 'Microsoft.VisualStudio.Azure.Containers.Tools.Targets'

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest

    steps:
      - uses: trossr32/outdated-packages-action@v1.7.0
        with:
          use-dotnet-outdated: true
          dotnet-solution-or-project-path: ${{ env.SOLUTION_PATH }}
          dotnet-exclude-packages: ${{ env.EXCLUDE_PACKAGES }}
          dotnet-version: '9.*.*'
          use-npm-outdated: true
          npm-project-directory: ${{ env.PROJECT_DIR }}